"""Run the exact same validation + analytics code the Lambda uses, offline.

    python scripts/local_pipeline.py                      # generate dirty data and process it
    python scripts/local_pipeline.py --input leads.csv    # process your own file
    python scripts/local_pipeline.py --sample-js          # also (re)build dashboard/sample-metrics.js

Outputs go to ./out : processed.csv, errors.json, metrics.json
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date, datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

import core  # noqa: E402
import generate_data  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", help="CSV to process (default: generate synthetic dirty data)")
    ap.add_argument("--rows", type=int, default=800)
    ap.add_argument("--out-dir", default="out")
    ap.add_argument("--sample-js", action="store_true", help="write dashboard/sample-metrics.js")
    args = ap.parse_args()

    today = date.today()
    if args.input:
        with open(args.input, encoding="utf-8-sig") as fh:
            text = fh.read()
    else:
        text = generate_data.generate(rows=args.rows, seed=7, dirty=True, today=today)

    result = core.parse_and_validate(text, today)
    metrics = core.compute_metrics(result.rows, today)

    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, "processed.csv"), "w", encoding="utf-8") as fh:
        fh.write(core.rows_to_csv(result.rows))
    with open(os.path.join(args.out_dir, "errors.json"), "w", encoding="utf-8") as fh:
        json.dump(result.errors, fh, indent=2)
    with open(os.path.join(args.out_dir, "metrics.json"), "w", encoding="utf-8") as fh:
        json.dump(metrics, fh, indent=2)

    t = metrics["totals"]
    print(f"rows read        : {result.total_rows}")
    print(f"valid (deduped)  : {len(result.rows)}")
    print(f"rejected         : {len(result.errors)}")
    print(f"duplicates       : {result.duplicates_removed}")
    print(f"conversion rate  : {t['conversion_rate']:.1%}")
    print(f"revenue (INR)    : {t['revenue']:,}")
    print(f"overdue follow-ups: {metrics['overdue_followups']['count']}")
    print(f"outputs in ./{args.out_dir}/")

    if args.sample_js:
        runs = [{
            "sk": datetime.now(timezone.utc).isoformat() + "#sample",
            "source_key": "raw/sample.csv",
            "rows_total": result.total_rows,
            "rows_valid": len(result.rows),
            "rows_rejected": len(result.errors),
            "duplicates_removed": result.duplicates_removed,
        }]
        metrics["meta"] = {"source_key": "raw/sample.csv (synthetic)",
                           "updated_at": datetime.now(timezone.utc).isoformat()}
        path = os.path.join(ROOT, "dashboard", "sample-metrics.js")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("// Generated by scripts/local_pipeline.py --sample-js. Synthetic data.\n")
            fh.write("window.SAMPLE_METRICS = " + json.dumps(metrics) + ";\n")
            fh.write("window.SAMPLE_RUNS = " + json.dumps(runs) + ";\n")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
